[2023-09-15T12:23:20.672+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: business_question.most_productive_artist manual__2023-09-15T12:23:15.576372+00:00 [queued]>
[2023-09-15T12:23:20.686+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: business_question.most_productive_artist manual__2023-09-15T12:23:15.576372+00:00 [queued]>
[2023-09-15T12:23:20.687+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-09-15T12:23:20.704+0000] {taskinstance.py:1350} INFO - Executing <Task(GenericTransfer): most_productive_artist> on 2023-09-15 12:23:15.576372+00:00
[2023-09-15T12:23:20.712+0000] {standard_task_runner.py:57} INFO - Started process 1759 to run task
[2023-09-15T12:23:20.717+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'business_question', 'most_productive_artist', 'manual__2023-09-15T12:23:15.576372+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/businesse.py', '--cfg-path', '/tmp/tmpgkdmic69']
[2023-09-15T12:23:20.719+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask most_productive_artist
[2023-09-15T12:23:20.775+0000] {task_command.py:410} INFO - Running <TaskInstance: business_question.most_productive_artist manual__2023-09-15T12:23:15.576372+00:00 [running]> on host 7b2f04a25b74
[2023-09-15T12:23:20.876+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Aldinoharyo' AIRFLOW_CTX_DAG_ID='business_question' AIRFLOW_CTX_TASK_ID='most_productive_artist' AIRFLOW_CTX_EXECUTION_DATE='2023-09-15T12:23:15.576372+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-15T12:23:15.576372+00:00'
[2023-09-15T12:23:20.890+0000] {base.py:73} INFO - Using connection ID 'destination' for task execution.
[2023-09-15T12:23:20.953+0000] {base.py:73} INFO - Using connection ID 'final_destination' for task execution.
[2023-09-15T12:23:21.030+0000] {generic_transfer.py:77} INFO - Extracting data from destination
[2023-09-15T12:23:21.031+0000] {generic_transfer.py:78} INFO - Executing: 
 
    SELECT "ArtistId", "ArtistName", COUNT("TrackId") as "TotalTrack"
    FROM "songs"
    GROUP BY "GenreName", "ArtistId", "ArtistName"
    ORDER BY "TotalTrack" DESC
    
[2023-09-15T12:23:21.040+0000] {base.py:73} INFO - Using connection ID 'destination' for task execution.
[2023-09-15T12:23:21.048+0000] {sql.py:375} INFO - Running statement: 
    SELECT "ArtistId", "ArtistName", COUNT("TrackId") as "TotalTrack"
    FROM "songs"
    GROUP BY "GenreName", "ArtistId", "ArtistName"
    ORDER BY "TotalTrack" DESC
    , parameters: None
[2023-09-15T12:23:21.054+0000] {sql.py:384} INFO - Rows affected: 233
[2023-09-15T12:23:21.056+0000] {generic_transfer.py:95} INFO - Running preoperator
[2023-09-15T12:23:21.056+0000] {generic_transfer.py:96} INFO - ['DROP TABLE IF EXISTS question2', '\n        CREATE TABLE question2 (\n        \n        "ArtistId" INT NOT NULL,\n        "ArtistName" VARCHAR(70),\n        "TotalTrack" NUMERIC(10,2) NOT NULL\n        \n    \n        )\n        ']
[2023-09-15T12:23:21.066+0000] {base.py:73} INFO - Using connection ID 'final_destination' for task execution.
[2023-09-15T12:23:21.071+0000] {sql.py:375} INFO - Running statement: DROP TABLE IF EXISTS question2, parameters: None
[2023-09-15T12:23:21.072+0000] {sql.py:375} INFO - Running statement: 
        CREATE TABLE question2 (
        
        "ArtistId" INT NOT NULL,
        "ArtistName" VARCHAR(70),
        "TotalTrack" NUMERIC(10,2) NOT NULL
        
    
        )
        , parameters: None
[2023-09-15T12:23:21.075+0000] {generic_transfer.py:105} INFO - Inserting rows into final_destination
[2023-09-15T12:23:21.084+0000] {base.py:73} INFO - Using connection ID 'final_destination' for task execution.
[2023-09-15T12:23:21.107+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/generic_transfer.py", line 106, in execute
    insert_rows(table=self.destination_table, rows=results, **self.insert_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 467, in insert_rows
    cur.execute(sql, values)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(70)

[2023-09-15T12:23:21.117+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=business_question, task_id=most_productive_artist, execution_date=20230915T122315, start_date=20230915T122320, end_date=20230915T122321
[2023-09-15T12:23:21.130+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 17 for task most_productive_artist (value too long for type character varying(70)
; 1759)
[2023-09-15T12:23:21.170+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-09-15T12:23:21.206+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
